language: python
sudo: false
python:
  - "2.7"
node_js:
  - "6"
before_install:
  - pip install --upgrade setuptools pip
script:
  - npm install less
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
